# On Windows MSVC, statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
#
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]


# See https://github.com/eclipse-paho/paho.mqtt.rust/issues/57
[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "link-self-contained=yes",
  "-C", "link-arg=-lc"
]